### ISSUE TITLE
Possible usage of filtering ungrammatical sentences?

### ISSUE THREAD

**Issue by yujianll** [zhaoyanpeng/cpcfg#1]
Hi, thanks for sharing the repo! I wonder if it's possible to use this pcfg to filter out ungrammatical sentences. For example, set some thresholds for the sentence probability and remove sentences that are below the threshold. If yes, how can I modify the code to get the probability of an input sentence?

Thanks!

**Comment by zhaoyanpeng** [comment]
Hi it is doable. You might need to [train](https://github.com/zhaoyanpeng/cpcfg#learning) a parser first and follow the evaluation [instructions](https://github.com/zhaoyanpeng/cpcfg#parsing) to load the parser. 

The sentence probability can be estimated by summing `nll` and `kl`:
https://github.com/zhaoyanpeng/cpcfg/blob/249a0168af729e04f2c17f6680e51cf0d443f3fd/pcfg/model/pcfg.py#L34-L35

Let me know if you have further questions.

**Comment by yujianll** [comment]
Thanks!
